version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - notes
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - notes
volumes:
  mongodb_data:
networks:
  notes:
    driver: bridge